// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package ocealis

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Bottle struct {
	ID               int32
	SenderID         pgtype.Int4
	MessageText      string
	BottleStyle      pgtype.Int4
	StartLat         pgtype.Float8
	StartLng         pgtype.Float8
	Hops             pgtype.Int4
	ScheduledRelease pgtype.Timestamptz
	IsRelease        pgtype.Bool
	CreatedAt        pgtype.Timestamptz
}

type BottleEvent struct {
	ID        int32
	BottleID  pgtype.Int4
	EventType string
	Lat       pgtype.Float8
	Lng       pgtype.Float8
	CreatedAt pgtype.Timestamptz
}

type User struct {
	ID        int32
	Nickname  string
	AvatarUrl pgtype.Text
	CreatedAt pgtype.Timestamptz
}
